### ISSUE TITLE
Renaming sections

### ISSUE THREAD

**Issue by franciscrot** [SAS-DHRH/dhcc-toolkit#1]
(1) Lizzy & I talked about those two sections near the end, and came up with this division:

**Grant Writing** (renamed Project Planning) 
Funding landscape, DMPs, Should you footprint?, Choosing research questions

**Working Practices** (renamed Decision Trees)
Using devices, OS, data traffic (renamed day-to-day working), communication methods, travel, catering

Does that work?

(2) Marty mentioned that renaming might be finicky. Would it be any easier to create a brand new section called WORKING PRACTICES, and cut and paste everything from DECISION TREES into it? And then just include a very short bit of placeholder text in DECISION TREES?

"We hope to include some visual decision support tools in this section in the future. These might draw especially on the evidence and recommendations in the Working Practices and Grant Writing sections. If you're interested in contributing to this section, please get in touch."

**Comment by martysteer** [comment]
Yes, that works nicely. I've moved the DECISION TREES content into `./toolkit/working-practices.md`, put that holding para in it place and published. All your FAQ changes are there too (refresh browser cache if not visiblez).

**Comment by franciscrot** [comment]
Perfect, cheers :)
