### ISSUE TITLE
Minicomp page

### ISSUE THREAD

**Issue by martysteer** [SAS-DHRH/dhcc-toolkit#10]
I've had a go at editing the minicomp page. Here's a summary of my changes. Hope makes sense. Happy to revert.

I raised the lower sections up to the top. Rationale was the intro about minicomp now leads to the minicomp principles section, then the system changes section, then types of systems (static/dynamic) and finally specific website tips and case studies.

The only substantive text I added was in the 'Reduce client side javascript' tips section, where I added some thinking about cost/benefit of using javascripts and the structural effects these decisions can have. It might be a bit ranty, so please say if the tone is too uneven. LOL!

**Comment by JennyBunn** [comment]
Hi there,
I took a look at this page just now and noticed a duplication of the section about the Python programming language - which appears just before the Tips for sustainable websites heading and also nearer the top under applying minicomp principles.

**Comment by martysteer** [comment]
Thankyou! Fixing now...

**Comment by JennyBunn** [comment]
No worries and btw I think the tone was fine - did not come across as ranty to me.

**Comment by martysteer** [comment]
Have fixed the dupe. Thx!

(Excellent... only ranty on the inside. Phew! LOL!)
