### ISSUE TITLE
Working Practices - videoconferencing

### ISSUE THREAD

**Issue by franciscrot** [SAS-DHRH/dhcc-toolkit#15]
More info to help compare different videoconferencing software, maybe explore different numbers of participants as well. (Slightly surprising result from that one study, that for Zoom five participants used less energy than two).

To confirm, but is it likely that the differences between different videoconferencing softwares will be less significant than changing the settings within any given software? (Turning off cameras, turning down resolution, etc.)

**Comment by erwilliamson** [comment]
Good point. Maybe for the time being we delete the empty 'Carbon footprint' column, we already say we don't know which is better and let us know if you do, maybe just follow that sentence with 'we have provided some details on accessibility and privacy as a first step'?

**Comment by drjwbaker** [comment]
This looks to have been resolved, so I'm closing

**Comment by drjwbaker** [comment]
This looks to have been resolved, so I'm closing
