### ISSUE TITLE
Maximal computing case study

### ISSUE THREAD

**Issue by cmohge1** [SAS-DHRH/dhcc-toolkit#17]
Who authored this section? https://sas-dhrh.github.io/dhcc-toolkit/toolkit/maximal-computing.html#case-study

Was it @jptmoore or @franciscrot ? I think it would be good to just name who ran the workshop to avoid confusion. Also add a link to it if you can. 

Thanks,
C

**Comment by franciscrot** [comment]
🙋

**Comment by franciscrot** [comment]
Don't really have anything to link to but will add my name
