### ISSUE TITLE
No citation file

### ISSUE THREAD

**Issue by drjwbaker** [SAS-DHRH/dhcc-toolkit#43]
The toolkit has no CITATION file, or clear convention for citation on the landing page. 

Suggest:

> Anne Baillot, James Baker, Jenny Bunn, Alex Cline, Michael Faerber, Charlotte Feidicker, Josephine Lethbridge, Matthew McConkey, John Moore, Christopher Ohge, Torsten Roeder, Martin Steer, Jo Lindsay Walton, and Elizabeth Williamson. (2024). The Digital Humanities Climate Coalition Toolkit. https://sas-dhrh.github.io/dhcc-toolkit/

**Comment by franciscrot** [comment]
Sounds good - can we add Nicolas Seymour-Smith, who has just contributed an excellent case study
