### ISSUE TITLE
Sustainable Preservation and Archiving

### ISSUE THREAD

**Issue by franciscrot** [SAS-DHRH/dhcc-toolkit#5]
Has a section gone missing? Anyone know about this?

In the Google doc, Anne mentioned: "What I would expect to find in this chapter would be considerations on data format, on structuring a data collection (maybe that would refer to the DMP part?) and on research infrastructures."

Should we integrate some / all of the former Sustainable Preservation and Archiving into the Project Planning section? Happy to do that ...

**Comment by franciscrot** [comment]
Here is the text from the Google doc. Useful? Where should it go?

3. Sustainable preservation and archiving [3](https://docs.google.com/document/d/1ZsGdnqdIUMdHUvrJorJeRH_CWSVjsbLJhCR4cHzSNAA/edit?usp=sharing)

“A place to begin this navigation is recognizing that heritage is an anchor: a lifeline that grounds us and provides security and connection in the midst of change. Heritage creates sense of community and attachment to place, which promote disaster recovery and collective action.”
[A.R. Siders and Marcy Rockman](https://www.arch.columbia.edu/books/reader/826-preservation-sustainability-and-equity#reader-anchor-1)

Sustainable preservation and archiving 

Sustainable preservation and archiving (curation and stewardship) starts with responsible creation and collection. Put simply, you should not create or collect anything without some consideration of your responsibility for (sustaining) it, and whether the limits you put on that are appropriate.

Ongoing curation and stewardship (whether of digital or physical material resources) does not come without cost (financial, environmental, etc.).This means that it is important to take responsibility for actively disposing of data and resources (such as project websites) if they are no longer required at the end of a project and/or the retention period set by funding bodies. So-called benign neglect (e.g. leaving data to rot on servers) is not benign to the planet. This responsibility goes beyond any commitments made to research participants to dispose of their data after a given time period.

Disposal does not necessarily mean immediate deletion. You may choose to hand over responsibility for data and resources to another steward at the end of your project and for them to manage potential deletion (or continuing upkeep) at a future date. This steward could be an academic publisher (in the case of journal outputs), a web archive (in the case of websites) or another form of research data repository. 

If handing over responsibility for the ongoing stewardship of material, you will wish to choose a steward who you feel will act towards your material in a way that aligns with your values, e.g. by paying attention to its own climate impact. You will also want to understand what kind of commitment they are making towards it, e.g. how long will they keep it, how will they make it available, do you trust them to look after it etc. You may wish to open up dialogue with potential stewards around climate, to raise awareness and share knowledge and best practice. 

As you hand over your responsibility for your data and resources you should also consider how you can best contribute towards ensuring the new steward’s ongoing care of it. Quantifying the financial costs of ongoing curation and stewardship is difficult, but there are a number of tools that may help in this regard:

[Curation Costs Exchange (curationexchange.org)](https://www.curationexchange.org/)
[Total Cost of Stewardship: Responsible Collection Building in Archives and Special Collections (oclc.org)](https://www.oclc.org/research/publications/2021/oclcresearch-total-cost-of-stewardship.html)
[Costing — UK Data Service](https://ukdataservice.ac.uk/learning-hub/research-data-management/plan-to-share/costing/)

Making a financial contribution towards ongoing upkeep is not typically costed within research funding applications, but there is perhaps an argument that it should. Alternatively, a contribution could be made in terms of working with the steward to reduce the cost to them of ‘taking on’ your material. This may involve your taking on the tasks of re-formatting the material, weeding out duplicate or unimportant material, and/or creating additional documentation to ensure that what remains is reusable by others. 

If you are passing on the outputs of your work to a different steward (or repository) from the one who was caring for the data on which that work was based, you could also consider contacting the original steward to let them know. This would allow them to realise some of the added benefit that has arisen from their part (in preserving the data in the first place) in your work (in undertaking the research using it). This can help them to demonstrate the value of their work to those who are making a financial contribution towards it. In some cases it may even be that you can contribute some aspects of your work (e.g. enhanced data about the data held by them) back to the original stewards of it.

Offline and nearline preservation

Data can be stored more sustainably by keeping it offline or “nearline” (meaning it is not available immediately, but can be made available with little or no human intervention). Sustainable preservation means considering offline storage or nearline storage. [Kilbride (2021)](https://www.dpconline.org/blog/digital-preservation-and-climate-change-provocation-to-and-from-cop26) comments:

[...] every touchpoint of a preservation workflow requires some energy – ingest, fixity check, migration and access for example. So as well as reducing the data volumes we need to ask how many times a file needs to checked for integrity. We need to question the assumption of large-scale format migration and normalization, and the carbon cost of storing and processing uncompressed files. We need to ask whether instant access – which means spinning disks – is always the best solution. Nearline or offline storage is less good for users but is much healthier for the planet. [(Kilbride 2021)](https://www.zotero.org/google-docs/?Ckrvj1)

A recent white paper by Fuji is enthusiastic about nearline / offline storage using tape:

Tape supports green datacenter initiatives by storing data offline without consuming energy. Tape systems can also serve as nearline or active-archive tiers of storage. This means that the data is available for productive use but does not consume processing power and requires minimal environmental resources while the data is not being used. [(Cooke et al. 2021)](https://www.zotero.org/google-docs/?lKUlCx)

Curation and stewardship for climate justice

What we choose to preserve, and how we preserve it, is part of the story. Another part of the story is how these collections are accessed and used. Collections can help to raise awareness and foster debate about climate justice. 

Collections can play a role in cultural heritage institutions acting as trusted spaces where publics form, get informed, enthused, and empowered. They can be used to support traditional knowledge, including Indigenous knowledge, and to connect such knowledge with broader climate actions and policies. Collections can be observatories where human embeddedness in nature is brought vividly to life. Some resources include:

[Climate Heritage Network](https://climateheritage.org/)
[European Association for Heritage Interpretation](https://interpret-europe.net/about-heritage-interpretation/)
[International Centre for the Study of the Preservation and Restoration of Cultural Property](https://ocm.iccrom.org/)
[Indigenous Archives Collective](https://indigenousarchives.net/)

There is widespread recognition that climate transition needs to be more participatory and democratic than is currently the case, both as a good in itself and to ensure that climate policy is effective. ‘Additional activities in the process of heritage interpretation are restoration, documentation and revitalisation of tangible and intangible cultural heritage. The volunteering activities imbue strong principles of democracy, equality, tolerance, nondiscrimination and inclusiveness for every participant’ [(Interpret Europe 2020)](https://www.zotero.org/google-docs/?Qa4prH)

Deepening democracy is challenging. [Communicating Climate Risk: A Toolkit](https://bit.ly/CommunicatingClimateRisk) suggests that a “‘campaigning’ mentality risks alienating people. Genuinely participatory processes allow for emergent scope”; it also cautions that “[m]ore vulnerable groups and individuals may also be those less able to access participatory processes”, which can then “replicate historical patterns of exclusion” [(Levontin and Walton 2021)](https://www.zotero.org/google-docs/?broken=qMfPRN). Technology theorist Andrew Feenberg writes: ‘Radical democratization presupposes the desire for increased responsibility and power, but the citizens of industrial societies today appear to be more anxious to “escape from freedom” than to enlarge its range. I will not argue with this view, but it is simply dogmatic to dismiss the possibility of a reversal of current trends. Things were different as recently as the 1960s and may change in the future as the full scope of worldwide environmental crisis finally sinks in” [(Feenberg 2002)](https://www.zotero.org/google-docs/?broken=l8lQPU).

The issues that cultural heritage professionals often address in their work, about when something is worth saving, can also illuminate the challenges and trade-offs of climate change adaptation in interesting ways.

Finally, collections can help with mainstreaming climate awareness. Climate change has been described as ‘everything change’. Curators can include climate change and climate justice angles, even when the climate is not the primary focus of a particular programme, exhibition, or event.

Further reading on sustainable preservation and archiving

Digital Preservation Coalition. ‘[Environmentally Sustainable Digital Preservation](https://www.dpconline.org/digipres/discover-good-practice/environmentally-sustainable-digital-preservation)’.

Cultural Adaptations. [Adapting our Culture toolkit](https://www.culturaladaptations.com/toolkit/adapting-our-culture-toolkit/). Includes advice on creating a climate adaptation plan, geared toward cultural institutions.

Brabec, Elizabeth, and Elizabeth Chilton. 2015. “Toward an Ecology of Cultural Heritage.” Change Over Time 5 (20): 266–307.

Parnitzke, Daniel. ‘[Finding Pleasure in Scarcity](http://pleasureinscarcity.com/)’. MA Thesis, Design Academy Eindhoven. 

Abbey, Heidi N. “[The Green Archivist: A Primer for Adopting Affordable, Environmentally Sustainable, and Socially Responsible Archival Management Practices](https://minds.wisconsin.edu/handle/1793/72389),” Archival Issues.

Kilbride, William. 2021. ‘[Digital Preservation and Climate Change: Provocation to and from COP26 - Digital Preservation Coalition](https://www.dpconline.org/blog/digital-preservation-and-climate-change-provocation-to-and-from-cop26)’. DCP Online.

**Comment by martysteer** [comment]
I'd prefer a new page with this content, but alternative location might be in the Working practices page, after the [publishing your data section](https://sas-dhrh.github.io/dhcc-toolkit/toolkit/working-practices.html#publishing-your-data). Thoughts?

**Comment by erwilliamson** [comment]
I would say that the main 'Sustainable preservation and archiving' section and 'offline/nearline' sections should go in Working Practices (condensed if possible). I'd still vote for changing Project Planning to be named Grant Writing if weren't too onerous to make the associated link changes, so it feels less like these two pages are stepping on each others toes. 

'Curation and stewardship for climate justice' feels like a slightly different beast - more generalist, less about practical working, perhaps it might even fit better in the climate change FAQs. Perhaps this section needs reorganising/rewriting to be primarily about climate justice and democratising transition, with a paragraph or two on how (digital) heritage collections can play a part in this (and then it links to See also section X in Working Practices).'

**Comment by franciscrot** [comment]
I have it locally as separate section but I can combine.

I think it would be nice to include *something* positive about the relationship between preservation and sustainability, so it doesn't feel like we're telling archivists off. Maybe I'll have a go at substantially shortening that section and smoothing the voice and style out? If it still feels like it doesn't work then I'll try it as a FAQ instead?

Will have a go at changing to Grant Writing too, I also like that toe distribution better

**Comment by franciscrot** [comment]
Sorry haven't done this yet, will do tomorrow!

**Comment by franciscrot** [comment]
Done this now - but leaving it open till it's been reviewed (@erwilliamson and maybe whoever originally wrote the preservation section?)

Should be fine for the launch event though :)

**Comment by erwilliamson** [comment]
Thanks for this, agreed it's fine for the launch event. A couple of suggestions:

- change section in Grant Writing that refers to this in Working Practices to 'Publishing and Archiving', as both sections are relevant for Grant Writing but we're saying for specific practices look there.
- in Working Practices, suggest that this section needs a heading in side bar, so there's 'Publishing your data' followed by 'Archiving your data' (nice to mirror the language).
- I think that the paragraph beginning 'The potential curation of preserved data' could be easier to parse. Can we identify the main point of this para and put that in bold to guide reader? What do we mean by potential curation? I'm not sure that the quote is clear enough without further context (what volunteering activities?). Perhaps beginning with something like 'Careful curation of collections data can contribute to climate justice awareness and foster debate...

**Comment by franciscrot** [comment]
Sounds perfect & I've had a go at these 3 bullets

**Comment by franciscrot** [comment]
Might want to revisit but feels closed for now!
