### ISSUE TITLE
WebP

### ISSUE THREAD

**Issue by franciscrot** [SAS-DHRH/dhcc-toolkit#7]
Should we make any images WebP, as we recommend?

https://github.com/SAS-DHRH/dhcc-toolkit/blob/main/content/toolkit/minimal-computing.md

**Comment by martysteer** [comment]
Have converted that table image on this page to webp (see other issue about my edits of the minicomp page). However webp is not compatible with all browsers yet. Technical solution is multi-source images which let browser pick the file to download. This is possible in hugocms but needs some theming jiggery pokery. I'd like to do this but for brevity I compressed the png and that's tiny enough! (I'll also do this to the other images before the launch event).
