### ISSUE TITLE
Travel and catering section location

### ISSUE THREAD

**Issue by erwilliamson** [SAS-DHRH/dhcc-toolkit#8]
Hi all, we now have a brief reference to the travel and catering section in the Working Practices doc, referring the reader to Project Planning. I'd be inclined to move this to Working Practices, since it relates to general work activity and not just projects. Plus that leaves the Project Planning section focusing clearly and solely on funding, DMPs, and research questions, which feels coherent. This would also work well if we did decide to go in and change the name of this section to Grant Writing (which we've left for now because of dependencies, I wasn't sure if we were returning to it at some point). But regardless, what do you think of moving the travel/catering wholly to Working Practices? Happy to be disagreed with, of course!

**Comment by franciscrot** [comment]
Sounds good - I'll give Travel a tidy and swap it round with the brief reference, if there are no objections

**Comment by franciscrot** [comment]
Done!
